# Site settings
encoding: utf-8
title: สังศิต ไสววรรณ
url: "https://sungsit.com"
description: >
  สังศิตเขียนบ้างในบางเวลา ...
baseurl: ""
twitter_username: gzix
github_username:  sungsit
lang: th
timezone: Asia/Bangkok
permalink: /:year-:month-:day-:title.html
paginate: 13
paginate_path: "/page/:num/"

excerpt_separator: <!--more-->


# Github
github:
  owner_name: "sungsit"
  owner_url: "https://github.com/sungsit"
  repository_url: "https://github.com/sungsit/sungsit.github.io"

# Github Pages Sitemap
gems:
  - jekyll-sitemap
  - jekyll-paginate

highlighter: pygments

# Build settings
markdown: kramdown



